### PR TITLE
fix: :bug: Fix the issue with fav images display

### LINKED ISSUE #73: Liked images doesnt appear immediately on favourites.

### PR DESCRIPTION
**Pull request by furkanmutlu**
## Fixes Issue

Closes #73 

## Changes proposed

Fix the issue with fav images display

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [ ] My change requires changes to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by elyessAR** [comment]
great job fixing the issue @furkanmutlu but I think there is an issue with the preview, when a user visit the app for the first time with no previous cache he can't like any gif until he refreshes the page, I'm not sure if this is only for me, can you please open incognito and visit the preview to check?
PS: this is only present with the preview deployment, I could not recreate it with the already deployed app.

**Comment by furkanmutlu** [comment]
> PS: this is only present with the preview deployment, I could not recreate it with the already deployed app.

I believe it should be fixed with last commit

**Comment by elyessAR** [comment]
> > PS: this is only present with the preview deployment, I could not recreate it with the already deployed app.
> 
> I believe it should be fixed with last commit

the preview deployment doesn't take in consideration the last commit? the code looks clean however the issue still present in preview.

**Comment by furkanmutlu** [comment]
> the preview deployment doesn't take in consideration the last commit? the code looks clean however the issue still present in preview.

@elyessAR fixed

**Review by elyessAR — APPROVED** [review]

**Pull request merged**
